### ISSUE TITLE
ReadTimeout to Docker Host

### ISSUE THREAD

**Issue by maksym-iv** [bcicen/dockerstats#13]
Hello,

I'm trying to launch Statsquid agent with command
`docker run --rm -i -t  --name=statsquid_agent_prod --link=statsquid_redis bcicen/statsquid agent  --redis statsquid_redis --docker tcp://HOST:PORT`
Because I have docker on remote host.

Firstly I got info messages like 
`2016-01-27 15:28:14: started collector for container 5c0f25491e59cc7021020e7e2`
but after 1-2 minutes I got exception error 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/statsquid/agent.py", line 73, in _collector
    stats = self.docker.stats(cid, decode=True)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 362, in stats
    return self._stream_helper(self._get(url, stream=True),
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 110, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 435, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='dev-1.aws.bkstg.com', port=2375): Read timed out. (read timeout=60)
```

I've checked connection from host where agent is launched, connection is successful.
Also I've tried to use tcp://HOST, http://HOST, but without any success.
Can you please help me to understand what am I doing wrong?

**Comment by bcicen** [comment]
@xmackex I've seen this issue come up several times, even with the latest Docker-py -- how many containers do you have running on the remote host?

It's worth noting that I haven't experienced this timeout (with any number of containers) running the agent on each host using the Docker unix socket.

**Comment by maksym-iv** [comment]
@bcicen I have ~60 containers. Is it possible to increase timeout?

**Comment by bcicen** [comment]
@xmackex fyi, this project is now deprecated in favor of https://github.com/bcicen/ctop
