### ISSUE TITLE
Error on start "KeyError: 'network'"

### ISSUE THREAD

**Issue by nik-kor** [bcicen/dockerstats#14]
``` bash
master_1 | Traceback (most recent call last):
master_1 |   File "/usr/bin/statsquid", line 9, in <module>
master_1 |     load_entry_point('statsquid==0.5', 'console_scripts', 'statsquid')()
master_1 |   File "build/bdist.linux-x86_64/egg/statsquid/cli.py", line 64, in main
master_1 |   File "build/bdist.linux-x86_64/egg/statsquid/listener.py", line 30, in __init__
master_1 |   File "build/bdist.linux-x86_64/egg/statsquid/listener.py", line 36, in run_forever
master_1 |   File "build/bdist.linux-x86_64/egg/statsquid/listener.py", line 71, in _process_msg
master_1 |   File "build/bdist.linux-x86_64/egg/statsquid/container.py", line 41, in append_stat
master_1 |   File "build/bdist.linux-x86_64/egg/statsquid/stat.py", line 10, in __getattr__
master_1 |     ST_DEV   = 2
master_1 | KeyError: 'network'
```

``` bash
➜  ~ docker -v
Docker version 1.9.1, build a34a1d5
```

Also, It's on Mac and docker-machine

So the top command shows nothing.

**Comment by bcicen** [comment]
https://github.com/bcicen/statsquid/commit/a53efb9fa6d6f4ba41840e48a84999956db63367 pushed to fix. Can you pull the latest image and give that a try?

**Comment by nik-kor** [comment]
I've got this 

``` bash
agent_1  | Traceback (most recent call last):
agent_1  |   File "/usr/bin/statsquid", line 9, in <module>
agent_1  |     load_entry_point('statsquid==0.5', 'console_scripts', 'statsquid')()
agent_1  |   File "build/bdist.linux-x86_64/egg/statsquid/cli.py", line 70, in main
agent_1  |   File "build/bdist.linux-x86_64/egg/statsquid/agent.py", line 27, in __init__
agent_1  |   File "/usr/lib/python2.7/site-packages/docker/api/daemon.py", line 33, in info
agent_1  |     return self._result(self._get(self._url("/info")), True)
agent_1  |   File "/usr/lib/python2.7/site-packages/docker/client.py", line 158, in _result
agent_1  |     self._raise_for_status(response)
agent_1  |   File "/usr/lib/python2.7/site-packages/docker/client.py", line 154, in _raise_for_status
agent_1  |     raise errors.APIError(e, response, explanation=explanation)
agent_1  | docker.errors.APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.22, server API version: 1.21)")
```

**Comment by bcicen** [comment]
Thanks, Docker client has been updated to use the auto-detected API version of the server https://github.com/bcicen/statsquid/commit/7e78c0a709cfe4935049eef6bac397421d78ebd2

**Comment by nik-kor** [comment]
it works! Thanks)
